# -*- coding: utf-8 -*-

CATEGORY_ANI = 'AN'
CATEGORY_COMIC = 'CM'
CATEGORY_GAME = 'GM'
CATEGORY_DOUJINSHI = 'DO'
CATEGORY_MOVIE = 'MO'
CATEGORY_DRAMA = 'DR'
CATEGORY_ETC = 'ET'
CATEGORY_MUSIC = 'MU'

CATEGORY_ANI_NAME = 'Anime'
CATEGORY_COMIC_NAME = 'Comic'
CATEGORY_GAME_NAME = 'Game'
CATEGORY_DOUJINSHI_NAME = 'Doujinshi'
CATEGORY_MOVIE_NAME = 'Movie'
CATEGORY_DRAMA_NAME = 'Drama'
CATEGORY_ETC_NAME = 'etc'
CATEGORY_MUSIC_NAME = 'Music'

def get_category_list():
  category_list = [
    [ CATEGORY_ANI, CATEGORY_ANI_NAME ],
    [ CATEGORY_COMIC, CATEGORY_COMIC_NAME ],
    [ CATEGORY_GAME, CATEGORY_GAME_NAME ],
    [ CATEGORY_DOUJINSHI, CATEGORY_DOUJINSHI_NAME],
    [ CATEGORY_MOVIE, CATEGORY_MOVIE_NAME ],
    [ CATEGORY_DRAMA, CATEGORY_DRAMA_NAME ],
    [ CATEGORY_MUSIC, CATEGORY_MUSIC_NAME ],
    [ CATEGORY_ETC, CATEGORY_ETC_NAME ]
    ]
  return category_list
